language:
    - python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.6
          env: TOXENV=py26
        - os: linux
          sudo: required
          python: 2.7
          env: TOXENV=py27
        - os: linux
          sudo: required
          python: 3.3
          env: TOXENV=py33
        - os: linux
          sudo: required
          python: 3.4
          env: TOXENV=py34
        - os: linux
          sudo: required
          python: 3.5
          env: TOXENV=py35
        - os: linux
          sudo: required
          python: 3.6
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=py2
        - os: osx
          language: generic
          env: TOXENV=py3

install:
    - ./.travis/install.sh

script:
    - echo "done"
